version: 2.1
jobs:
  publish:
    docker: 
      - image: squidfunk/mkdocs-material
    steps:
      - add_ssh_keys:
          fingerprints:
            - '44:0a:d3:97:eb:78:06:89:3b:d8:24:bd:11:79:53:79'
      - checkout
      - run:
          name: Build
          command: |
            mkdocs build
      - run:
          name: Cleanup
          command: |
            mv .git /tmp/
            cp -r site/* /tmp/
      - run:
          name: Publish
          command: |
            cd /tmp/
            apk add --no-cache git openssh-client
            git config user.email "circleci@circle.com"
            git config user.name "circleci"
            git checkout --orphan gh-pages
            git add . && git commit -m "[ci skip] Publish"
            git push --force origin gh-pages

workflows:
  version: 2
  publish: 
    jobs: 
    - publish:
        filters: 
          branches: 
            only: master
